site_name: HPC Documentation
#theme: mkdocs
use_directory_urls: false
nav:
  - Home: index.md
  - Overview: overview.md
  - Contributing: contributing.md

# Copyright footer
copyright: 'Copyright &copy; University of Bern, IT Service Office'
# Social links at botoom right
repo_name: 'hpc-unibe-ch/hpc-docs'
repo_url: 'https://github.com/hpc-unibe-ch/hpc-docs'
edit_uri: ''

# Configuration
theme:
  name: material

extra_css:
 - 'stylesheets/unibe.css'

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc


extra:
  social:
    - type: 'github'
      link: 'https://github.com/ubelix'

