site_name: HPC Documentation
#theme: mkdocs
use_directory_urls: false
nav:
  - Home: index.md
  - Overview: overview.md
  - Code of Conduct: code-of-conduct.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - File Transfer: user-guide/file-transfer.md
    - Job Management with Slurm:
      - Job Submission: user-guide/job-management/job-submission.md
      - Monitoring Jobs: user-guide/job-management/monitoring-jobs.md
      - Deleting Jobs: user-guide/job-management/deleting-jobs.md
      - Array Jobs with Slurm: user-guide/job-management/array-jobs.md
      - GPUs: user-guide/job-management/gpus.md
      - Interactive Jobs: user-guide/job-management/interactive-jobs.md
      - Investigating a Job Failure: user-guide/job-management/investigating-job-failure.md
      - Checkpointing: user-guide/job-management/checkpointing.md
    - Software:
      - Pre-Installed Software: user-guide/software/pre-installed-software.md
    - File System Quota: user-guide/file-system-quota.md
  - Contributing: contributing.md

# Copyright footer
copyright: 'Copyright &copy; University of Bern, IT Service Office'
# Social links at botoom right
repo_name: 'hpc-unibe-ch/hpc-docs'
repo_url: 'https://github.com/hpc-unibe-ch/hpc-docs'
edit_uri: ''

# Configuration
theme:
  name: material

extra_css:
 - 'stylesheets/unibe.css'

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences


extra:
  social:
    - type: 'github'
      link: 'https://github.com/ubelix'

