site_name: HPC Documentation
#theme: mkdocs
use_directory_urls: false
nav:
  - IMPORTANT..Home Migration: HOME_migration.md 
  - PLAN..Workspaces: overview_workspaces.md
  - Quick Start: quick-start.md
  - Getting Started:
    - Code of Conduct: code-of-conduct.md
    - UniBE HPC system "UBELIX": getting-Started/ubelix-overview.md
    - Accounts and Activation: getting-Started/account.md
    - Accessing the HPCs: getting-Started/login-ssh.md
      #      - software for connecting to the HPCs:
      #      - Port Forwarding:
    - Workspaces: getting-Started/workspaces.md
    - SSH customization: getting-Started/ssh-customization.md
  - Workspaces:
    - Overview: hpc-workspaces/workspaces.md
    - Workspace management: hpc-workspaces/management.md
    - Software environment: hpc-workspaces/environment.md
    - Monitoring: hpc-workspaces/monitoring.md
  - Job handling:
    - Submitting jobs: slurm/submission.md
    #      - Parallel execution:
    - Monitoring Jobs: slurm/monitoring-jobs.md
    - Deleting Jobs: slurm/deleting-jobs.md
    - Array Jobs with Slurm: slurm/array-jobs.md
    - GPUs: slurm/gpus.md
    - Interactive Jobs: slurm/interactive-jobs.md
    - Investigating a Job Failure: slurm/investigating-job-failure.md
    - Checkpointing: slurm/checkpointing.md
    - Fair Share: slurm/fair-share.md
    #
  - Software:
    - HPC software environment: software/hpc-modules.md
    - Pre-Installed Software: software/pre-installed-software.md
    - Installing Custom Software: software/installing-custom-software.md
    - EasyBuild: software/EasyBuild.md
    - Supported Applications:
      - Terminal Multiplexer (tmux): software/terminal-multiplexer-tmux.md
      - CUDA: software/CUDA.md
      - Matlab: software/matlab.md
      - Python: software/python.md
      - JupyterLab: software/JupyterLab.md
      - R: software/r.md
      - Relion: software/relion.md
      - Singularity: software/singularity.md
  - Storage:
    - Overview: file-system/filesystem-overview.md
    - File System Quota: file-system/quota.md
    - Moving files to and from the HPCs: file-system/file-transfer.md
  - Code of Conduct: code-of-conduct.md
  - FAQ: general/faq.md
  - Hall of Fame: halloffame.md
      #
      #
      #  - Home: index.md
      #  - User Guide:
      #    - Getting Started: user-guide/getting-started.md
      #    - File Transfer: user-guide/file-transfer.md
      #    - Job Management with Slurm:

# Copyright footer
copyright: 'Copyright &copy; University of Bern, IT Service Office'
# Social links at botoom right
repo_name: 'hpc-unibe-ch/hpc-docs'
repo_url: 'https://github.com/hpc-unibe-ch/hpc-docs'
edit_uri: ''

# Configuration
theme:
  name: material

extra_css:
 - 'stylesheets/unibe.css'

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list


extra:
  social:
    - type: 'github'
      link: 'https://github.com/ubelix'

