site_name: HPC Documentation
#theme: mkdocs
use_directory_urls: false
nav:
  - Getting Started:
    - Code of Conduct: code-of-conduct.md
    - UniBE HPC system Ubelix: getting-Started/ubelix-overview.md
    - Accounts and Workspaces: getting-Started/account-workspaces.md
      #      - Activating your campus account:
      #      - creating a HPC workspace:
      #      - join an existing HPC workspace:
      #      - workspace extension:
    - Accessing the HPCs: getting-Started/login-ssh.md
      #      - software for connecting to the HPCs:
      #      - Port Forwarding:
    - First Steps:
      - Moving files to and from the HPCs: file-system/file-transfer.md
      - Submitting your first job: slurm/submission.md
      #      - Parallel execution:
      - Monitoring Jobs: slurm/monitoring-jobs.md
      - Deleting Jobs: slurm/deleting-jobs.md
      - Array Jobs with Slurm: slurm/array-jobs.md
      - GPUs: slurm/gpus.md
      - Interactive Jobs: slurm/interactive-jobs.md
      - Investigating a Job Failure: slurm/investigating-job-failure.md
      - Checkpointing: slurm/checkpointing.md
      #
      #  - Scientific Computing:
      #    - HPC software environment:
      #    - Pre-Installed Software: user-guide/software/pre-installed-software.md
      #    - Installing Custom Software: user-guide/software/installing-custom-software.md
      #    - Supported Applications:
      #      - Terminal Multiplexer (tmux): user-guide/software/terminal-multiplexer-tmux.md
      #      - Matlab: user-guide/software/matlab.md
      #      - Python: user-guide/software/python.md
      #      - JupyterLab: user-guide/software/JupyterLab.md
      #      - R: user-guide/software/r.md
      #      - Relion: user-guide/software/relion.md
      #      - Singularity: user-guide/software/singularity.md
      #  - Storage:
      #    - File System Quota: user-guide/file-system-quota.md
      #  - General:
      #    - FAQ: user-guide/faq.md
      #    - Hall of Fame: halloffame.md
      #
      #
      #  - Home: index.md
      #  - User Guide:
      #    - Getting Started: user-guide/getting-started.md
      #    - File Transfer: user-guide/file-transfer.md
      #    - Job Management with Slurm:

# Copyright footer
copyright: 'Copyright &copy; University of Bern, IT Service Office'
# Social links at botoom right
repo_name: 'hpc-unibe-ch/hpc-docs'
repo_url: 'https://github.com/hpc-unibe-ch/hpc-docs'
edit_uri: ''

# Configuration
theme:
  name: material

extra_css:
 - 'stylesheets/unibe.css'

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list


extra:
  social:
    - type: 'github'
      link: 'https://github.com/ubelix'

